### ISSUE TITLE
crash on boot when using with forgified fabric api

### ISSUE THREAD

**Issue by danildrem3** [TheAGamePlayer/The-Pure-Suffering-Mod#16]
ver: PureSuffering-1.21.1-1.6.6.0B NEOFORGE
Neoforge 21.1.73
Mods: 
PureSuffering-1.21.1-1.6.6.0B
forgified-fabric-api-0.104.0+2.0.13+1.21.1

[debug.log](https://github.com/user-attachments/files/17590379/debug.log)

**Comment by TheAGamePlayer** [comment]
This is quite an interesting bug since Its difficult to figure out who's at fault here. I can attempt to make my code work differently to avoid the problem, however I do believe the error **"[31окт.2024 19:19:31.717] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/multiplayer/ClientLevel (java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER)"** that is shown right before the crash would imply that ForgifiedFabric is breaking some NeoForge mods so that Fabric mods can load properly. No promises I can provide a work around, but I'll give my best effort before I ask the other mod creator.

**Comment by kaiserdragon217** [comment]
Have you tried to test with neo forge version 21.1.74 along with forgified fabric version API 0.104.0+2.0.18+1.21.1? 
You are using forgified fabric version "0.104.0+2.0.13+1.21.1" which maybe an outdated version. Pure-suffering 1.6.6.0B seems to work on my end.

video of it working: https://youtu.be/W36xIttYyng

**Comment by danildrem3** [comment]
Problem only with server. Single world working fine

**Comment by TheAGamePlayer** [comment]
Thanks for letting us know, I'll be testing this later today.

**Comment by TheAGamePlayer** [comment]
This should be fixed with Pure Suffering 1.6.6.1B, let me know if it works for you as well.

**Comment by danildrem3** [comment]
Thanks! It's working now

**Comment by TheAGamePlayer** [comment]
Going to close since this seems to be resolved :)
