### ISSUE TITLE
mod spawning pigs

### ISSUE THREAD

**Issue by scooterwackyruler** [TheAGamePlayer/The-Pure-Suffering-Mod#8]
im creating my own datapack for this mod, adding invasions with modded mobs, but when i have the mobs in the .json it just spawns pigs instead of the mobs i want
im trying to spawn new creepers added by the creeper overhaul mod but its also spawning the pigs when i try and spawn tnt and minion creepers from the mutant monsters mod, which confuses me because of the datapack that spawns the mobs from there, and it spawns those just fine
im playing with the most recent 1.19.2 version

**Comment by TheAGamePlayer** [comment]
Pigs spawn either because you have a mob id spelled incorrectly, you have a mob id that doesn't exist written, or lastly an entity that isn't a mob is chosen to spawn. Seeing that you're trying to spawn tnt in an invasion, the only way that tnt could be spawned in an invasion is as a cluster entity, rather than under the MobSpawnList. See https://github.com/TheAGamePlayer/The-Pure-Suffering-Mod/blob/main/src/main/resources/data/puresuffering/invasion_types/super_storm.json as an example. You'll want to have the tnt entity added under the ClusterEntitiesList. This will make the tnt spawn before the rest of the mobs, but it may cause your mobs to blow up when the tnt goes off, so be sure to add a weight to it :>

**Comment by TheAGamePlayer** [comment]
Being that it is 3 weeks later I will assume you solved the problem, I will reopen the issue if problems are found.
